In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("./data/salesdaily.csv")

In [4]:
data.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,1/2/2014,0.0,3.67,3.4,32.40,7.0,0.0,0.0,2.0,2014,1,248,Thursday
1,1/3/2014,8.0,4.00,4.4,50.60,16.0,0.0,20.0,4.0,2014,1,276,Friday
2,1/4/2014,2.0,1.00,6.5,61.85,10.0,0.0,9.0,1.0,2014,1,276,Saturday
3,1/5/2014,4.0,3.00,7.0,41.10,8.0,0.0,3.0,0.0,2014,1,276,Sunday
4,1/6/2014,5.0,1.00,4.5,21.70,16.0,2.0,6.0,2.0,2014,1,276,Monday

## QUESTIONS

- What are the total sales quantities for each drug category (ATC code)?

- Which individual drug brands have the highest total sales?

- Which three drugs have the highest sales in January 2015, July 2016, September 2017.

- Which drug has sold the most often in 2017?

- Which drug category has the highest average daily sales?

- Are respiratory drugs (R03) sold more during specific months?

In [12]:
# What are the total sales quantities for each drug category (ATC code)?
ATC_CODE = ['M01AB', 'M01AE', 'N02BA', 'N02BE', 'N05B', 'N05C', 'R03','R06']
total_sales = data[ATC_CODE].sum()

In [18]:
total_sales.sort_values(ascending=True)

N05C      1249.958333
R06       6107.817500
N02BA     8172.209000
M01AE     8204.618646
M01AB    10600.937083
R03      11608.822917
N05B     18645.737500
N02BE    63005.402708
dtype: float64

In [19]:
# Which individual drug brands have the highest total sales?
total_sales.max()

63005.40270834

In [21]:
#  Which three drugs have the highest sales in January 2015, July 2016, September 2017.
data["datum"] = pd.to_datetime(data["datum"])

In [22]:
data.head()

,datum,M01AB,M01AE,N02BA,N02BE,N05B,N05C,R03,R06,Year,Month,Hour,Weekday Name
0,2014-01-02,0.0,3.67,3.4,32.40,7.0,0.0,0.0,2.0,2014,1,248,Thursday
1,2014-01-03,8.0,4.00,4.4,50.60,16.0,0.0,20.0,4.0,2014,1,276,Friday
2,2014-01-04,2.0,1.00,6.5,61.85,10.0,0.0,9.0,1.0,2014,1,276,Saturday
3,2014-01-05,4.0,3.00,7.0,41.10,8.0,0.0,3.0,0.0,2014,1,276,Sunday
4,2014-01-06,5.0,1.00,4.5,21.70,16.0,2.0,6.0,2.0,2014,1,276,Monday

In [23]:
df = data.copy()

In [26]:
conditions = (
    (df['datum'].dt.year == 2015) & (df['datum'].dt.month == 1) |  # Jan 2015
    (df['datum'].dt.year == 2016) & (df['datum'].dt.month == 7) |  # Jul 2016
    (df['datum'].dt.year == 2017) & (df['datum'].dt.month == 9)    # Sep 2017
)
filter_dates = df[conditions]

In [30]:
filter_dates[ATC_CODE].sum().sort_values(ascending=False)[:3]

N02BE    2560.352000
N05B      926.000000
M01AB     468.768333
dtype: float64

In [31]:
# Which drug has sold the most often in 2017?
most_sold = df[df['datum'].dt.year == 2017]

In [41]:
most_sold[ATC_CODE].sum().sort_values()[:1]

N05C    180.333333
dtype: float64